/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simplest.possible.implementation;

import java.util.List;

import static java.util.Collections.emptyList;

public class PrimeFactors {
    public List of(int number) {
        if (number == 1) return emptyList();
        if (number == 2) return List.of(2);
        return null;
    }
}
